# remove confirmation on closing
confirm_os_window_close 0

# The basic colors
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC

# Cursor colors
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #F5E0DC

# set font and font size
font_size 11
font_family Symbols Nerd Font

# resize font
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0

# set opacity
background_opacity         0.95
dynamic_background_opacity yes
